### ISSUE TITLE
Missing PrivacyInfo.xcprivacy file

### ISSUE THREAD

**Issue by hotngui** [googleads/swift-package-manager-google-user-messaging-platform#10]
The release notes for 2.3.0 say its been updated to support the new Privacy Manifest, but I do not see the file anywhere in the repo.

**Comment by stsandro** [comment]
This is a binary package. You have to look into the [zip file](https://github.com/googleads/swift-package-manager-google-user-messaging-platform/blob/cfe8b2ae16b9bc81f4cdf1d1a12a01a452489c32/Package.swift#L42) of the binary target. If you do so you'll find it there in the folders of the XCFramework's subfolders for the architecture, e.g. ios-arm64. 

This issue can now be closed.
