### ISSUE TITLE
Conflicting nullability on the UMPConsentForm

### ISSUE THREAD

**Issue by tiago-queiros** [googleads/swift-package-manager-google-user-messaging-platform#12]
Hi,

On our project we've set the `TREAT_WARNINGS_AS_ERRORS` flag to `YES` and we've noticed the following error in the `UMPConsentForm`:
> Conflicting nullability specifier on return types, 'nullable' conflicts with existing specifier 'nonnull'

This error arises from the use of `- (nullable instancetype)init NS_UNAVAILABLE;`, where the nullable specifier is causing a conflict.

Is there any chance this could be fixed?

I’ve attached an example project to help demonstrate the issue.
[UserMessagingExample.zip](https://github.com/user-attachments/files/15550633/UserMessagingExample.zip)

Thanks!

**Comment by malandr2** [comment]
Hi @tiago-queiros, this looks like something that we can address - can you a create a new thread on the [AdMob Developers Forum](https://groups.google.com/g/google-admob-ads-sdk) for it to be properly triaged? Thanks!

Closing this out.

**Comment by tiago-queiros** [comment]
Posting the link [here](https://groups.google.com/g/google-admob-ads-sdk/c/rdEbzFQk2kA) in case anyone want's to follow up
