### ISSUE TITLE
Update User Messaging Platform documentation to mention SwiftPM as a possibility

### ISSUE THREAD

**Issue by kendy** [googleads/swift-package-manager-google-user-messaging-platform#6]
It is awesome that this exists, thank you! Would be great to update the documentation at:

https://developers.google.com/admob/ios/privacy

to mention that it is possible to use Swift Package Manager too; the page lists only CocoaPods and Manual download at the moment.

I'd report it on the page, but found no way how do that (or missed it if it is possible)... Thank you in advance!

**Comment by malandr2** [comment]
Hi @kendy, thank you for flagging this. 

I created an internal change to update https://developers.google.com/admob/ios/privacy to reflect SPM support. The change will be reflected as soon as it is approved/submitted. Closing this ticket out as there is no other steps needed. 

Thanks!
